// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARbGD35bs6bj1fggr_rB-O8I4LmYvHr2E',
    appId: '1:752292786093:android:2427f0202c5964260e7b24',
    messagingSenderId: '752292786093',
    projectId: 'testt-32d71',
    storageBucket: 'testt-32d71.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaSWkrB1aRRX9Ko76obHGgWYVRYx84fwE',
    appId: '1:752292786093:ios:cad7758711b20e290e7b24',
    messagingSenderId: '752292786093',
    projectId: 'testt-32d71',
    storageBucket: 'testt-32d71.appspot.com',
    androidClientId: '752292786093-5s53rnfdlbbala6hf4npj6vn95crj70t.apps.googleusercontent.com',
    iosClientId: '752292786093-esdbtr6b2p6qj9q7r8g4eo64i200jiac.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialapp',
  );
}
